# when using the default proxy server port
# local_backend: true
# backend:
#   name: git-gateway
backend:
  name: git-gateway
  branch: dev


media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Site Settings"
        name: "settings"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
